title: <h1 style="font-family:verdana;">This is a heading</h1>
logo: assets/img/namelogo.png
description: Quality job, every time! <a href="tel:0432253216">Call us now</a> <i class="fa-solid fa-phone"></i>
show_downloads: false
favicon: true
color-scheme: auto
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

# You can find fonts from https://iconify.design or https://fontawesome.com. Below is just an example illustrating how to use custom icons
sidebar:
  - name: Home
    icon: <i class="fa-solid fa-house"></i>
    link: index.html
  - name: LED Lighting
    icon: <i class="fa-regular fa-lightbulb"></i>
    link: ledlighting.html
  - name: About Us
    icon: <i class="fa-solid fa-user-group"></i>
    link: about-us.html
  - name: Contact Us
    icon: <i class="fa-solid fa-envelope"></i>
    link: contact-us.html
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/woodcockelectrical
  - name: Project Repository
    icon: <svg xmlns="http://www.w3.org/2000/svg" aria-hidden="true" role="img" style="vertical-align:-0.125em;" width="1em" height="1em" preserveAspectRatio="xMidYMid meet" viewBox="0 0 16 16"><g fill="currentColor"><path d="M12.643 15C13.979 15 15 13.845 15 12.5V5H1v7.5C1 13.845 2.021 15 3.357 15h9.286zM5.5 7h5a.5.5 0 0 1 0 1h-5a.5.5 0 0 1 0-1zM.8 1a.8.8 0 0 0-.8.8V3a.8.8 0 0 0 .8.8h14.4A.8.8 0 0 0 16 3V1.8a.8.8 0 0 0-.8-.8H.8z"/></g></svg>
    link: https://github.com/woodcockelectrical/main

# https://github.com/github/pages-gem/issues/399#issuecomment-301827749
# When running locally, we run into the following error â€”
# GitHub Metadata: No GitHub API authentication could be found. Some fields may be missing or have incorrect data.
# adding this avoids it
github: [metadata]
